### ISSUE TITLE
No popup from Tools > WakaTime Settings 

### ISSUE THREAD

**Issue by frankcalise** [salaros/monodevelop-wakatime#3]
I'm unable to add my API key into the WakaTime Settings. I click this item from the Tools menu and nothing seems to pop up. Is there a file I can manually set this in to work around?

Xamarin 5.9.6 (build 23)
Windows 8.1 Pro

**Comment by alanhamlett** [comment]
You can manually create the `~/.wakatime.cfg` file following [this example](https://github.com/wakatime/wakatime#configuring). Only the `[settings]` and `api_key` lines are required.

**Comment by frankcalise** [comment]
What directory are you expecting this to be in on a Windows machine?

C:\Users\XYZ\AppData\Local or Roaming?

**Comment by alanhamlett** [comment]
Currently it's at `C:\Users\XYZ\.wakatime.cfg`, but we will move it to `AppData\Roaming\WakaTime` sometime in the future.

**Comment by salaros** [comment]
Hi, this was fixed in the latest versions of the extension

**Comment by salaros** [comment]
This issue was moved to CodeCavePro/monodevelop-wakatime#6
