### ISSUE TITLE
[Bug] Detecting non-code files as coding

### ISSUE THREAD

**Issue by claunia** [salaros/monodevelop-wakatime#4]
WakaTime plugin for MonoDevelop is detecting assemblies (*.exe and *.dll) and debug info (*.mdb) files as code, while it should, of course, ignore them.

**Comment by alanhamlett** [comment]
For now, add them to your `~/.wakatime.cfg` file under `exclude` config:
https://github.com/wakatime/wakatime#configuring

**Comment by salaros** [comment]
@alanhamlett I haven't found any exclusion logic in Visual Studio addin code, so I suppose that there is some problem with events I've in MonoDevelop / Xamarin Studio addin

**Comment by alanhamlett** [comment]
@salaros, the exclusion logic is in Python in wakatime-core:
https://github.com/wakatime/wakatime/blob/master/wakatime/main.py#L242

It's just a temporary solution to prevent logging time to non-code files. A better solution is to blacklist non-code files in C# space so it works for all users.

**Comment by salaros** [comment]
@alanhamlett Yes, I got it, but I mean is this issue is common to both VS and MD/XS addins?
I have never noticed VS addin reporting activity on *.mdb/dll/exe files

**Comment by alanhamlett** [comment]
Theres no code in the VS plugin to prevent reporting activity on binary files. I've personally never opened a binary file in Visual Studio so I'm not sure if it would report activity or not.

**Comment by salaros** [comment]
This issue was moved to CodeCavePro/monodevelop-wakatime#5
