### ISSUE TITLE
have to remove wakatime-master folder to start logging

### ISSUE THREAD

**Issue by s1m0n1stv4n** [salaros/monodevelop-wakatime#5]
Using monodevelop-unity 5.9.6 in osx, loggin simply doesn't start. Oddly if I remove the generated wakatime-master folder from the home folder and restart monodevelop, logging works as expected for this session. So I have to remove the folder every time before restarting monodevelop for wakatime to work. Any suggestions?

**Comment by salaros** [comment]
Hi, are you using the lastest version available from extension repository (extension version should be 1.0.3)? Anyway tomorrow I will get access to my Mac and will try to dig into this problem.

**Comment by s1m0n1stv4n** [comment]
Yes, the latest. Thanks for looking into it!

**Comment by salaros** [comment]
This issue was moved to CodeCavePro/monodevelop-wakatime#4
